### ISSUE TITLE
More documentation for newbies

### ISSUE THREAD

**Issue by ameer** [waoai/react-image-annotate#10]
Hi. Thanks for your great work. I'm fairly new to React and I want to use this library for one of my project. I run the below command and everything has been installed successfully.

`npm install react-image-annotate`

But here is the problem. I don't know how/where to use these lines to run the editor:

```
import ReactImageAnnotate from "react-image-annotate"
const App = () => (
  <ReactImageAnnotate
    selectedImage="https://example.com/image1.png"
    taskDescription="# Draw region around each face\n\nInclude chin and hair."
    images={[{ src: "https://example.com/image1.png", name: "Image 1" }]}
    regionClsList={["Man Face", "Woman Face"]}
  />
)
```

Any help would be appreciated. Thanks.

**Comment by seveibar** [comment]
hey @ameer, take a look at Create React App. It'll show you how to create a project. After you create the project, you can place that line in the `App.js` file.

**Comment by ameer** [comment]
Thanks again!

**Comment by ameer** [comment]
Hi. I managed to get it up and ready. But I got this error very soon after running the app:

```
index.js:1375 Warning: Failed prop type: The prop `open` is marked as required in `ForwardRef(Dialog)`, but its value is `undefined`.
    in ForwardRef(Dialog) (created by WithStyles(ForwardRef(Dialog)))
```
and after I edited my image and hit the save button I got this error:

```
Uncaught TypeError: onExit is not a function
    at dispatch (index.js:53) //node_modules/react-image-annotate/Annotator/index.js
``` 

Where is the problem?

**Comment by seveibar** [comment]
You'll need to define the `onExit` function. What do you want to do with the output? If you want to save it, you'll need to save it somewhere. Many people save to the cloud, some save to local storage.

The warning is a minor issue, nothing to worry about.

**Comment by seveibar** [comment]
@ameer I introduced some additional documentation in 357beae to the README that I hope helps you understand how you can manipulate react-image-annotate for your application.

**Comment by ameer** [comment]
Great! I'll test it and let you know about the results. Thanks again and good luck!
