### ISSUE TITLE
Add a delta mouse movement value to create Annotations for bounding boxes.

### ISSUE THREAD

**Issue by ajmaln** [waoai/react-image-annotate#26]
#### Bug:
- While using bounding box, whenever I click on the canvas, another bounding box annotation is created. 
- If I try to select one of the existing annotation, another bounding box is created

#### Expected behaviour:
- Do not create bounding box annotation on click, instead add threshold distance for mouse movement to create annotation.
- Do not create annotation when clicking on labels in canvas.

**Comment by seveibar** [comment]
Thanks @ajmaln, I've seen this bug as well and it's pretty annoying.

**Comment by seveibar** [comment]
Annotations can sometimes contain other annotations, so we may need a new prop `allowOverlap`

**Comment by ajmaln** [comment]
@seveibar  I would like to check the event handlers for drawing the boundboxes. Could you please guide me to it?

**Comment by seveibar** [comment]
Hey @ajmaln, the event system has many layers, so its a bit difficult to answer this question. e.g. drawing is different than selecting. The latest version from yesterday has some fixes you might be interested in using before trying to fix the software yourself.

**Comment by ajmaln** [comment]
Thank you @seveibar, will check them out.

**Comment by seveibar** [comment]
The issues presented here are now resolved, if they come up again it should be a new issue.
