### ISSUE TITLE
Latest commit breaks the component

### ISSUE THREAD

**Issue by plumpNation** [waoai/react-image-annotate#35]
https://github.com/waoai/react-image-annotate/pull/31

This *seems* to break images completely. I only started looking at the codebase today, so please take this with a pinch of salt.

If videoTime is 0, which it is by default, then === undefined will not by true and the video tag will always render instead of the img tag.

**Comment by seveibar** [comment]
yep this is fixed now

**Comment by seveibar** [comment]
more specifically fixed here: https://github.com/waoai/react-image-annotate/commit/62bbb395b77b1b7bb4250a5c503b78e15bc5d73e and released as 0.2.3, thanks for reporting!
