### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by CarlosUvaSilva** [waoai/react-image-annotate#37]
I have this error when I try to import react-image-annotate in my Create React App

```
./node_modules/material-survey/components/Survey/index.js
Module parse failed: Unexpected token (143:16)
You may need an appropriate loader to handle this file type.
|     }
|   }, _react2.default.createElement(_SurveyQuestion2.default, {
|     question: { ...q,
|       defaultAnswer: defaultAnswers[q.name]
|     },
``` 

Can somebody help me please

**Comment by seveibar** [comment]
The segment of code posted is related to material survey. I wonder if this is due to a recent version? We're using react-image-annotate in the [universal data tool](https://universaldatatool.com) without a problem and that's based on create react app.

**Comment by seveibar** [comment]
Do you have a repository that reproduces the issue? That would let us investigate sooner

**Comment by CarlosUvaSilva** [comment]
@seveibar thanks for your reply.

I had Reat 16 but an old version of CRA, after I upgraded my react-scripts package it started to work
