### ISSUE TITLE
missing PixelSize

### ISSUE THREAD

**Issue by CarlosUvaSilva** [waoai/react-image-annotate#40]
For some reason the pixelSize object for each region is missing now. It was working a couple of days ago. did you commit something or maybe I deleted necessary props? I can't find the reason

**Comment by seveibar** [comment]
@CarlosUvaSilva Can you describe the expected behavior? How do we reproduce it?

**Comment by CarlosUvaSilva** [comment]
@seveibar thanks for the quick reply

```
"images": [
      {
        "src": "blob:http://localhost:3000/315b2476-8c0f-484b-8d7f-6c157cc22702",
        "name": "food",
        "pixelSize": {
          "w": 512,
          "h": 512
        },
        "regions": [
          {
            "type": "box",
            "x": 0.43148148,
            "y": 0.12592593,
            "w": 0.03522554,
            "h": 0.050829522,
            "highlighted": true,
            "editingLabels": false,
            "color": "hsl(317,100%,50%)",
            "id": "6869745681035326",
            "cls": "bread",
            "tags": [
              "not-text"
            ]
          }
        ]
      }
```

this is the images array from the object returned by onExit I had before when it was working.

the "new" array I get now doesn't have that pixelSize object

**Comment by seveibar** [comment]
Is your version 0.2.5? If it was working in a previous release you could try 0.2.4 and we would know its a regression.

**Comment by CarlosUvaSilva** [comment]
I have version 0.3.0

**Comment by seveibar** [comment]
We should also document this feature when we fix whatever bug is causing it not to show up.

**Comment by seveibar** [comment]
I've found the bug. Fix coming later tonight.
