### ISSUE TITLE
option to manually add text and classify regions on images

### ISSUE THREAD

**Issue by sreevardhanreddi** [waoai/react-image-annotate#53]
Hi, @seveibar I just checked out your project. It looks great, I need some help.

I have few doubts

* when I draw a region, I only have the option to select from the existing classes and tags, I wanted to know if there was an **option to manually enter something in the text field** and classify a region?

* In the **regions object** 'x','y','w' and 'h' values are less than the actual image size, how do I get the actual coordinates? should I multiply 'x' with the width of the image, 'y' with the height of the image, 'w' with the width of the image, and 'h' with the height of the image?

Thanks

**Comment by seveibar** [comment]
* Classifications must be predefined in the props (I'd very much like to add dynamic classification addition, PRs welcome :)
*  Percentage of image :)

**Comment by sreevardhanreddi** [comment]
@seveibar I'll be happy to add the feature, could you explain to me how the mouse events and the labels are connected together?

For the second point, should I multiply x, y, w, and h values by 100 to get the true values?

**Comment by seveibar** [comment]
* I think you'll want to look in the RegionEditLabel component.

* If you want the pixel values, multiply by the width and height of the image

**Comment by sreevardhanreddi** [comment]
* @seveibar Thanks a lot, I will check the RegionEditLabel component.

* So for the pixel values,  I should multiply 'x' with the width of the image, 'y' with the height of the image, 'w' with the width of the image, and 'h' with the height of the image.
am I right?

**Comment by ajitStephen** [comment]
> * RegionEditLabel
Sample regions data:
`{
  "image": {
    "src": "....",
    "name": "DSC03843.JPG",
    "pixelSize": { "w": 7952, "h": 4472 },
    "regions": [
      {
        "type": "box",
        "x": 0.14187556952658198,
        "y": 0.09422492401215805,
        "w": 0.14358491373774562,
        "h": 0.060790273556231,
        "highlighted": false,
        "editingLabels": false,
        "color": "#2196f3",
        "cls": "Broken Concrete",
        "id": "09735222254753118"
      },
    ]
  }
}
`

For pixel values of x,y,w,h, should multiply like this:
x = (pixelSize.w * pixelSize.h * regions.x)
y = (pixelSize.w * pixelSize.h * regions.y)
w = (pixelSize.w * pixelSize.h * regions.w)
h =  (pixelSize.w * pixelSize.h * regions.h)

I am trying to use these values to crop image by [jimp](https://www.npmjs.com/package/jimp)

**Comment by arhmnsh** [comment]
@seveibar @sreevardhanreddi Could you please show us how you implemented this functionality?
Tried to check RegionEditLabel, but couldn't figure it out.

**Comment by sreevardhanreddi** [comment]
hey @arhmnsh you can check this [pr](https://github.com/UniversalDataTool/react-image-annotate/pull/55/files)

**Comment by arhmnsh** [comment]
@sreevardhanreddi Thanks for the quick reply. Actually, I went thru it but still couldn't figure it out. Could you please share a basic sample or codesandbox like this: https://codesandbox.io/s/react-image-annotate-example-forked-8t9w7?file=/src/App.js?
