### ISSUE TITLE
Read input image as bytes?

### ISSUE THREAD

**Issue by HTenkanen** [waoai/react-image-annotate#61]
Hi guys! 

Thanks for creating this awesome tool! Have been playing around with it a little bit and it seems very promising. 👍 

I have one question though: now it seems that the image source needs to be an URLs to the image.. I was wondering that would it be possible to read the image directly from bytes for example? I have a MongoDB backend and I use Python as middleware that would allow me to pass the images to the frontend directly e.g. as Bytes (or some other in-memory format)? Do you think this would be a difficult thing to add/change? I would like to avoid saving the image to disk for this purpose..

I went through the codebase but as it is quite extensive so decided to ask first before spending more time trying to implement something silly without knowing too much about the insides of the project.. 🙂    

@seveibar

**Comment by seveibar** [comment]
You could base64 encode the image and pass it in as a data uri.

**Comment by seveibar** [comment]
If you can give a link to an example serialized image we can probably figure it out.

**Comment by HTenkanen** [comment]
@seveibar Awesome, thanks a lot for your quick answer! I'll test the base64 encoded image. Sounds like a good idea. 👍
